language: c

git:
  depth: 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8-multilib

compiler:
  - gcc-4.8
  - clang

os:
  - linux
  - osx

script:
  - mkdir -p build
  - cd build
  - cmake "Unix Makefiles" ..
  - make
